### ISSUE TITLE
React Hooks 강의해주실 수 있을까요??

### ISSUE THREAD

**Issue by hsh2001** [egoing/react-tutorial-example#1]
항상 좋은 강의 감사합니다. 덕분에 많은 지식을 얻고 있습니다 😭 

최근에 리액트에 Hooks 라는 기능이 추가되며 컴포넌트를 생성할 때 클래스형보다 Hooks를 사용한 함수 컴포넌트를 사용할 것이 권장되고 있다고 합니다. React Hooks 라는 주제의 강의도 나중에 기회가 되신다면 추가해주셨으면 합니다. 감사합니다 🙇

**Comment by hsh2001** [comment]
https://ko.reactjs.org/docs/hooks-intro.html

**Comment by egoing** [comment]
훅도 한번 강의로 다뤄볼께요~

**Comment by hsh2001** [comment]
감사합니다 😊
